In [44]:
from gammapy.utils.random import get_random_state
import numpy as np
import astropy.units as u

In [40]:
random_state = np.random.RandomState(seed=0)
random_state = get_random_state(random_state)

In [41]:
random_state

RandomState(MT19937) at 0x11E3C4888

In [42]:
random_state.randint(2)

0

In [53]:
from astropy.time import Time
t1 = Time([1.0, 2, 3], format="mjd")

In [54]:
t1

<Time object: scale='utc' format='mjd' value=[1. 2. 3.]>

In [56]:
t1.mjd[0]

1.0

In [78]:
energy = [1, 1, 1, 1, 1] * u.TeV


In [81]:
time = [2,3] * u.hr

In [84]:
energy * time[:, np.newaxis]

<Quantity [[2., 2., 2., 2., 2.],
           [3., 3., 3., 3., 3.]] h TeV>

In [68]:
time[:, np.newaxis, np.newaxis]

TypeError: list indices must be integers or slices, not tuple

In [75]:
from astropy.coordinates import SkyCoord, Angle

In [77]:

SkyCoord(83.633083, 22.0145, unit="deg", frame="icrs").galactic

<SkyCoord (Galactic): (l, b) in deg
    (184.55745771, -5.78435696)>

In [86]:
import scipy.integrate as integrate


In [151]:
t = np.array([1,2,3,4,5,6,10])


In [280]:
def evaluate(times):
    #return np.power(times,2)
    return np.ones_like(times)

In [281]:
times = np.array([1,2,3,4,5,6,10])
f = evaluate(times)
integrate.trapz(f,times)
func = interp1d(times, f)

In [283]:
%%time
integrate.quad(func,1,10)[0]

CPU times: user 3.46 ms, sys: 1.31 ms, total: 4.77 ms
Wall time: 4.62 ms


9.0

In [230]:
f = evaluate(t)

In [216]:
f = np.power([0,1],2)

In [177]:
f

array([0, 1])

In [181]:
integrate.trapz()

In [155]:
np.exp(-1) - np.exp(-10)

0.36783404124167984

In [156]:
t

array([ 1,  2,  3,  4,  5,  6, 10])

In [157]:
f

array([3.67879441e-01, 1.35335283e-01, 4.97870684e-02, 1.83156389e-02,
       6.73794700e-03, 2.47875218e-03, 4.53999298e-05])

In [198]:
from scipy.interpolate import interp1d

In [205]:
func = interp1d(times, f)

In [212]:
np.cumsum?

In [235]:
class ABC:
    def return1():
        return 1
    
    def return0():
        return 0
    

class CDE(ABC):
    def return3():
        return 3

In [237]:
CDE.return1()

1

In [244]:
from gammapy.data import GTI
gti = GTI.read('$GAMMAPY_DATA/hess-dl3-dr1//data/hess_dl3_dr1_obs_id_023523.fits.gz')

In [279]:
gti.time_start.mjd

array([53343.92234009])

In [284]:
from gammapy.utils.integrate import evaluate_integral_pwl, trapz_loglog

In [ ]:
trapz_loglog(evaluate, energies)

In [285]:
from gammapy.maps.utils import edges_from_lo_hi

In [290]:
e = edges_from_lo_hi([1,2,3],[4,5,6])

In [291]:
e